package com.kh.search.dao;

import com.kh.search.model.KhApi;

public interface KhApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_api
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_api
     *
     * @mbggenerated
     */
    int insert(KhApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_api
     *
     * @mbggenerated
     */
    int insertSelective(KhApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_api
     *
     * @mbggenerated
     */
    KhApi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_api
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KhApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_api
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KhApi record);
}