package com.kh.search.model;

import java.io.Serializable;

public class KhApi implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_api.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_api.kh_num
     *
     * @mbggenerated
     */
    private String khNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kh_api
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_api.id
     *
     * @return the value of kh_api.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_api.id
     *
     * @param id the value for kh_api.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_api.kh_num
     *
     * @return the value of kh_api.kh_num
     *
     * @mbggenerated
     */
    public String getKhNum() {
        return khNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_api.kh_num
     *
     * @param khNum the value for kh_api.kh_num
     *
     * @mbggenerated
     */
    public void setKhNum(String khNum) {
        this.khNum = khNum == null ? null : khNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_api
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", khNum=").append(khNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_api
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        KhApi other = (KhApi) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getKhNum() == null ? other.getKhNum() == null : this.getKhNum().equals(other.getKhNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_api
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getKhNum() == null) ? 0 : getKhNum().hashCode());
        return result;
    }
}