server:
  port: 8080

spring:
  datasource:
    name: aliyunmysql
    url: jdbc:mysql://116.62.129.244:3306/khdb?characterEncoding=utf8&useSSL=false
    username: chenadmin
    password: Chenadmin0.
    # 数据库驱动
    driver-class-name: com.mysql.jdbc.Driver

    redis:
        # 连接地址
        host: 127.0.0.1
        # 端口号
        port: 6379
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 10000
          # 连接池中的最大空闲连接
          max-idle: 200
          # 连接池中的最小空闲连接
          min-idle: 5
        # 连接超时时间，0为不限制
        timeout: 0
        # 数据库索引
        database: 0

mybatis:
  type-aliases-package: com.kh.search
  mapper-locations: classpath:mapper/*.xml

